# logtype can take: debug, info, notice, warning, error, critical
#logtype = "info"
logtype = "debug"

[mpdserver]
ip = "localhost"
port = 6600

[ginserver]
port = 8060
jwtSecretKey = "secret key"
login = "admin"
password = "admin"
pem = ""
key = ""